function forex(id, pair, base, quote, decimals = quote === "JPY" ? 2 : 4) {
  return {
    id,
    pair,
    base,
    quote,
    market: "forex",
    decimals,
    timeframe: "1d",
  };
}

function crypto(id, pair, symbol, decimals = 4) {
  return {
    id,
    pair,
    base: pair.split("/")[0],
    quote: pair.split("/")[1],
    market: "crypto",
    symbol,
    decimals,
    timeframe: "15m",
  };
}

export const FOREX_PAIRS = [
  forex("eurusd", "EUR/USD", "EUR", "USD"),
  forex("gbpusd", "GBP/USD", "GBP", "USD"),
  forex("usdjpy", "USD/JPY", "USD", "JPY", 2),
  forex("usdchf", "USD/CHF", "USD", "CHF"),
  forex("audusd", "AUD/USD", "AUD", "USD"),
  forex("nzdusd", "NZD/USD", "NZD", "USD"),
  forex("usdcad", "USD/CAD", "USD", "CAD"),
  forex("eurjpy", "EUR/JPY", "EUR", "JPY", 2),
  forex("gbpjpy", "GBP/JPY", "GBP", "JPY", 2),
  forex("eurgbp", "EUR/GBP", "EUR", "GBP"),
  forex("eurchf", "EUR/CHF", "EUR", "CHF"),
  forex("eurcad", "EUR/CAD", "EUR", "CAD"),
  forex("euraud", "EUR/AUD", "EUR", "AUD"),
  forex("eurnzd", "EUR/NZD", "EUR", "NZD"),
  forex("gbpchf", "GBP/CHF", "GBP", "CHF"),
  forex("gbpcad", "GBP/CAD", "GBP", "CAD"),
  forex("gbpaud", "GBP/AUD", "GBP", "AUD"),
  forex("gbpnzd", "GBP/NZD", "GBP", "NZD"),
  forex("audjpy", "AUD/JPY", "AUD", "JPY", 2),
  forex("audcad", "AUD/CAD", "AUD", "CAD"),
  forex("audchf", "AUD/CHF", "AUD", "CHF"),
  forex("nzdjpy", "NZD/JPY", "NZD", "JPY", 2),
  forex("nzdcad", "NZD/CAD", "NZD", "CAD"),
  forex("nzdchf", "NZD/CHF", "NZD", "CHF"),
  forex("cadjpy", "CAD/JPY", "CAD", "JPY", 2),
  forex("cadchf", "CAD/CHF", "CAD", "CHF"),
  forex("chfjpy", "CHF/JPY", "CHF", "JPY", 2),
  forex("audnzd", "AUD/NZD", "AUD", "NZD"),
  forex("eursek", "EUR/SEK", "EUR", "SEK"),
  forex("eurnok", "EUR/NOK", "EUR", "NOK"),
  forex("gbpsek", "GBP/SEK", "GBP", "SEK"),
  forex("usdsek", "USD/SEK", "USD", "SEK"),
  forex("usdnok", "USD/NOK", "USD", "NOK"),
  forex("eurdkk", "EUR/DKK", "EUR", "DKK"),
  forex("eurpln", "EUR/PLN", "EUR", "PLN"),
  forex("usdsgd", "USD/SGD", "USD", "SGD"),
  forex("eursgd", "EUR/SGD", "EUR", "SGD"),
  forex("gbpsgd", "GBP/SGD", "GBP", "SGD"),
  forex("usdhkd", "USD/HKD", "USD", "HKD"),
  forex("eurhkd", "EUR/HKD", "EUR", "HKD"),
];

export const CRYPTO_PAIRS = [
  crypto("btcusdt", "BTC/USDT", "BTCUSDT", 2),
  crypto("ethusdt", "ETH/USDT", "ETHUSDT", 2),
  crypto("bnbusdt", "BNB/USDT", "BNBUSDT", 2),
  crypto("solusdt", "SOL/USDT", "SOLUSDT", 2),
  crypto("xrpusdt", "XRP/USDT", "XRPUSDT", 5),
  crypto("adausdt", "ADA/USDT", "ADAUSDT", 5),
  crypto("dogeusdt", "DOGE/USDT", "DOGEUSDT", 6),
  crypto("trxusdt", "TRX/USDT", "TRXUSDT", 5),
  crypto("linkusdt", "LINK/USDT", "LINKUSDT", 3),
  crypto("avaxusdt", "AVAX/USDT", "AVAXUSDT", 3),
  crypto("dotusdt", "DOT/USDT", "DOTUSDT", 3),
  crypto("tonusdt", "TON/USDT", "TONUSDT", 3),
  crypto("ltcusdt", "LTC/USDT", "LTCUSDT", 2),
  crypto("bchusdt", "BCH/USDT", "BCHUSDT", 2),
  crypto("uniusdt", "UNI/USDT", "UNIUSDT", 3),
  crypto("xlmusdt", "XLM/USDT", "XLMUSDT", 5),
  crypto("etcusdt", "ETC/USDT", "ETCUSDT", 3),
  crypto("filusdt", "FIL/USDT", "FILUSDT", 3),
  crypto("atomusdt", "ATOM/USDT", "ATOMUSDT", 3),
  crypto("nearusdt", "NEAR/USDT", "NEARUSDT", 4),
  crypto("icpusdt", "ICP/USDT", "ICPUSDT", 3),
  crypto("aptusdt", "APT/USDT", "APTUSDT", 3),
  crypto("arbusdt", "ARB/USDT", "ARBUSDT", 4),
  crypto("opusdt", "OP/USDT", "OPUSDT", 4),
  crypto("injusdt", "INJ/USDT", "INJUSDT", 3),
  crypto("vetusdt", "VET/USDT", "VETUSDT", 6),
  crypto("suiusdt", "SUI/USDT", "SUIUSDT", 4),
  crypto("shibusdt", "SHIB/USDT", "SHIBUSDT", 8),
  crypto("pepeusdt", "PEPE/USDT", "PEPEUSDT", 8),
  crypto("seiusdt", "SEI/USDT", "SEIUSDT", 5),
  crypto("jupusdt", "JUP/USDT", "JUPUSDT", 5),
  crypto("wifusdt", "WIF/USDT", "WIFUSDT", 4),
  crypto("fetusdt", "FET/USDT", "FETUSDT", 4),
  crypto("renderusdt", "RENDER/USDT", "RENDERUSDT", 4),
  crypto("grtusdt", "GRT/USDT", "GRTUSDT", 5),
  crypto("sandusdt", "SAND/USDT", "SANDUSDT", 5),
  crypto("manausdt", "MANA/USDT", "MANAUSDT", 5),
  crypto("axsusdt", "AXS/USDT", "AXSUSDT", 3),
  crypto("egldusdt", "EGLD/USDT", "EGLDUSDT", 3),
  crypto("hbarusdt", "HBAR/USDT", "HBARUSDT", 6),
  crypto("algousdt", "ALGO/USDT", "ALGOUSDT", 5),
  crypto("xtzusdt", "XTZ/USDT", "XTZUSDT", 4),
  crypto("eosusdt", "EOS/USDT", "EOSUSDT", 4),
  crypto("aaveusdt", "AAVE/USDT", "AAVEUSDT", 2),
  crypto("mkrusdt", "MKR/USDT", "MKRUSDT", 2),
  crypto("compusdt", "COMP/USDT", "COMPUSDT", 2),
  crypto("snxusdt", "SNX/USDT", "SNXUSDT", 4),
  crypto("thetausdt", "THETA/USDT", "THETAUSDT", 4),
  crypto("flowusdt", "FLOW/USDT", "FLOWUSDT", 4),
  crypto("kavausdt", "KAVA/USDT", "KAVAUSDT", 4),
  crypto("chzusdt", "CHZ/USDT", "CHZUSDT", 5),
  crypto("enjusdt", "ENJ/USDT", "ENJUSDT", 5),
  crypto("crvusdt", "CRV/USDT", "CRVUSDT", 5),
  crypto("1inchusdt", "1INCH/USDT", "1INCHUSDT", 5),
  crypto("ldousdt", "LDO/USDT", "LDOUSDT", 4),
  crypto("runeusdt", "RUNE/USDT", "RUNEUSDT", 4),
  crypto("imxusdt", "IMX/USDT", "IMXUSDT", 4),
  crypto("neousdt", "NEO/USDT", "NEOUSDT", 3),
  crypto("qtumusdt", "QTUM/USDT", "QTUMUSDT", 4),
  crypto("zecusdt", "ZEC/USDT", "ZECUSDT", 2),
  crypto("dashusdt", "DASH/USDT", "DASHUSDT", 2),
  crypto("ksmusdt", "KSM/USDT", "KSMUSDT", 3),
  crypto("stxusdt", "STX/USDT", "STXUSDT", 4),
  crypto("roseusdt", "ROSE/USDT", "ROSEUSDT", 6),
  crypto("blurusdt", "BLUR/USDT", "BLURUSDT", 5),
  crypto("apeusdt", "APE/USDT", "APEUSDT", 4),
  crypto("dydxusdt", "DYDX/USDT", "DYDXUSDT", 4),
  crypto("cakeusdt", "CAKE/USDT", "CAKEUSDT", 4),
  crypto("tiausdt", "TIA/USDT", "TIAUSDT", 3),
  crypto("ftmusdt", "FTM/USDT", "FTMUSDT", 5),
  crypto("galausdt", "GALA/USDT", "GALAUSDT", 6),
  crypto("cfxusdt", "CFX/USDT", "CFXUSDT", 5),
  crypto("iotausdt", "IOTA/USDT", "IOTAUSDT", 5),
  crypto("zilusdt", "ZIL/USDT", "ZILUSDT", 6),
];

export const SUPPORTED_PAIRS = [...FOREX_PAIRS, ...CRYPTO_PAIRS];

export function getPairById(id) {
  return SUPPORTED_PAIRS.find((pair) => pair.id === id) || null;
}

export function getPairLabelList() {
  return SUPPORTED_PAIRS.map((pair) => pair.pair);
}
